version: '3.1'
 
services:
  database:
    extends:
      file: ./services/database/docker-compose.yaml
      service: database
  
  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yaml
      service: pgadmin
