# Use postgres/example user/password credentials
version: '3.1'

services:

  # api:
  #   build: ./services/api
  #   environment:
  #     PORT: 8080
  #   ports:
  #     - 5000:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGPORT: 5001
    ports:
      - 5001:5001

  adminer:
    image: adminer
    restart: always
    ports:
      - 5002:8080
