version: '3.1'

services:  
  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yaml
      service: pgadmin

  zookeeper:
    extends:
      file: ./services/kafka/docker-compose.yaml
      service: zookeeper
    depends_on:
      loki:
        condition: service_started

  broker:
    extends:
      file: ./services/kafka/docker-compose.yaml
      service: broker
    depends_on:
      zookeeper:
        condition: service_started
      loki:
        condition: service_started

  grafana_database:
    extends:
      file: ./services/grafana/docker-compose.yaml
      service: grafana_database
    depends_on:
      loki:
        condition: service_started

  grafana:
    extends:
      file: ./services/grafana/docker-compose.yaml
      service: grafana
    depends_on:
      grafana_database:
        condition: service_healthy
      loki:
        condition: service_started

  loki:
    extends:
      file: ./services/grafana/docker-compose.yaml
      service: loki
