version: '3.1'

services:

  api:
    extends:
      file: ./services/api/docker-compose.yaml
      service: api
 
  database:
    extends:
      file: ./services/database/docker-compose.yaml
      service: database
  
  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yaml
      service: pgadmin
