version: '3.1'

services:
  github_store:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      START_DATE: ${START_DATE}
      COPY_BUFFER_LENGTH: ${COPY_BUFFER_LENGTH}
