package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
)

// Text is the resolver for the text field.
func (r *queryResolver) Text(ctx context.Context) (string, error) {
	var text string
	err := r.Database.QueryRow(context.Background(), "select 'Hello, world!'").Scan(&text)
	return text, err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
