// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TimePoint struct {
	Time   int      `json:"Time"`
	Values []*Value `json:"Values"`
}

type Value struct {
	Name  string `json:"Name"`
	Value int    `json:"Value"`
}
