// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	Key     string `json:"key"`
	Type    string `json:"type"`
	Payload string `json:"payload"`
	Created string `json:"created"`
}

type Organization struct {
	Key     string `json:"key"`
	Login   string `json:"login"`
	Name    string `json:"name"`
	Created string `json:"created"`
}
